#!/usr/bin/env ruby
#
# Start a console that initializes the gem
#
require "irb"
require "rubygems"

begin
  require 'wirble'
  Wirble.init
  Wirble.colorize
rescue LoadError
  STDERR.puts "To enable colorized and tab completed run 'gem install wirble'"
end

$: << "#{File.dirname(__FILE__)}/../lib"
load "#{File.dirname(__FILE__)}/../lib/localite.rb"

I18n.load_path += Dir["#{File.dirname(__FILE__)}/../test/i18n/*.yml"]

IRB.start
